### ISSUE TITLE
Vulnerabilities in dev dependencies

### ISSUE THREAD

**Issue by schoenbergerb** [Online-Payments/sdk-nodejs#1]
Liebe Leute,

ist euch eigentlich bewusst das dieses 💩 SDK hier nur so strotzt vor Sicherheitslücken????

`npm audit` 
- 4 KRITISCHE Sicherheitslücken
- 4 auf HOCH
- 15 moderate

Das kann man unmöglich irgendwo einbauen!!!!!!

🤬

**Comment by online-payments-support-team** [comment]
Dear schoenbergerb, thanks for raising this issue. This will be picked up and fixed with the following release.

Please note that the vulnerabilities are not present in the production version of the app, so using the SDK in your application will not expose vulnerabilities.

Kind regards,
Online Payment support team

**Comment by online-payments-support-team** [comment]
Dear @schoenbergerb,

The vulnerabilities have been fixed in [release 4.5.1](https://github.com/Online-Payments/sdk-nodejs/releases/tag/4.5.1).

Kind regards,
Online Payments support team
